version: 2.1

executors:
  default:
    docker:
      - image: eclipse-temurin:17-jdk
    working_directory: ~/project

jobs:
  build_and_test:
    executor: default
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
      MAVEN_CLI_OPTS: "-B -e -V"
    steps:
      - checkout

      - run:
          name: 🔧 Installing dependencies
          command: |
            apt-get update && apt-get install -y wget gnupg2 curl software-properties-common apt-transport-https unzip
            # Install Chrome
            mkdir -p /etc/apt/keyrings
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /etc/apt/keyrings/google-chrome.gpg
            echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
            apt-get update
            apt-get install -y google-chrome-stable
            # Install ChromeDriver
            export LATEST=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -N https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/
            chmod +x /usr/local/bin/chromedriver
            # Git & Maven
            apt-get install -y git maven
            git --version
            mvn -version

      - run:
          name: 🚀 Run Maven Tests
          command: |
            echo "📂 Current directory:$(pwd)"
            ls -la
            mvn clean test -DsuiteFile=testng.xml $MAVEN_CLI_OPTS

      - store_artifacts:
          path: target/surefire-reports
          destination: surefire-reports

      - store_artifacts:
          path: target
          destination: target-html
       

workflows:
  version: 2
  build_and_test_flow:
    jobs:
      - build_and_test
