version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  build_and_test:
    jobs:
      - build
